/*
 * Programski Jezici
 *
 * Ovaj API pruža pristup skupu podataka opisuje razne programske jezike te njihove detalje i funkcionalnosti. 
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	sw "github.com/mf51721/OR_lab/goapi"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(router.Run(":8080"))
}
